### ISSUE TITLE
explain_local raises "AttributeError: 'Series' object has no attribute 'iterrows'"

### ISSUE THREAD

**Issue by leoncena** [dandolodavid/ACME#1]
Hello,

Is it possible that the local explanation contains a bug? The following appears for me, although a series was also passed in the example notebook (as it also says in the documentation). Regarding the code, I stick to the demo notebook.

Am I missing something or is this a bug?

Reference: https://github.com/dandolodavid/ACME/blob/master/notebook/ACME%20classification.ipynb

Error:
....
in predictACME(model, series, features, percentile_functions, meta_table, task, score_function, class_to_analyze)
    348     Z_list.append(baseline)
    349     meta_list.append({'feature':feature_table.index.unique()[0],
    350                     'quantile':get_exact_quantile(percentile_functions[feature],baseline[feature])[0],
...
   5900 ):
   5901     return self[name]
-> 5902 return object.__getattribute__(self, name)

AttributeError: 'Series' object has no attribute 'iterrows'

Cheers

**Comment by dandolodavid** [comment]
Hello, thank you for report. I tried to run the notebook in the link but it run to the end without any error. 
I'm currently using version statwolfACME==2.1.1.
